spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      # Use ErrorHandlingDeserializer as the entry point
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Delegate the actual JSON work to the JsonDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "com.user_service.*"

  # PostgresSQL Database Connection Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/orderDB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

Kafka.topics:
  userTopic: user-topic
  userCreatedTopic: user-created-topic